{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.resilience4j",
    "module": "resilience4j-framework-common",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-circuitbreaker",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-ratelimiter",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-retry",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-bulkhead",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-timelimiter",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-micrometer",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "resilience4j-framework-common-2.3.0.jar",
          "url": "resilience4j-framework-common-2.3.0.jar",
          "size": 100027,
          "sha512": "d1ee7d0f2eb8a8c753a36b83b8592ee5d63bd9f8ad9a83541662ca1a4401f9f3af288dcd2eb4945b1435578816cd5931af8d3a75e8c6c07ed27bd73c383ff9f6",
          "sha256": "362dfc4c3f11325a242cce7712ea70a47ea23068f97c43b002038b5e1c18d5a6",
          "sha1": "deeea5a5d8ea1d4fa56c2d8bdad33ae5eba5211a",
          "md5": "608a740951fc5224a7ec49067cdd6c81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-circuitbreaker",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-ratelimiter",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-retry",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-bulkhead",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-timelimiter",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-micrometer",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "resilience4j-framework-common-2.3.0.jar",
          "url": "resilience4j-framework-common-2.3.0.jar",
          "size": 100027,
          "sha512": "d1ee7d0f2eb8a8c753a36b83b8592ee5d63bd9f8ad9a83541662ca1a4401f9f3af288dcd2eb4945b1435578816cd5931af8d3a75e8c6c07ed27bd73c383ff9f6",
          "sha256": "362dfc4c3f11325a242cce7712ea70a47ea23068f97c43b002038b5e1c18d5a6",
          "sha1": "deeea5a5d8ea1d4fa56c2d8bdad33ae5eba5211a",
          "md5": "608a740951fc5224a7ec49067cdd6c81"
        }
      ]
    }
  ]
}
