{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-validation",
    "version": "3.5.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.11"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.52"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.3.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-3.5.11.jar",
          "url": "spring-boot-starter-validation-3.5.11.jar",
          "size": 4769,
          "sha512": "8681c7c2c1b5884bed4b1ffaf13a951c67df6170b0dfaacd4650f82be1416bc13c2ea5ff4ef81b236bd6737821bccd63d5eb589b3c5278060ce89959174843d2",
          "sha256": "df99f17cb50fb7bc11c9f402f98d7ef326c87e6753c0a7bb8add8c58934ff8ec",
          "sha1": "903eefb6eab302617b0f01cc6d65664343bff2a7",
          "md5": "70bfde429862e7a8102386f6971e458d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.11"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.52"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.3.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-3.5.11.jar",
          "url": "spring-boot-starter-validation-3.5.11.jar",
          "size": 4769,
          "sha512": "8681c7c2c1b5884bed4b1ffaf13a951c67df6170b0dfaacd4650f82be1416bc13c2ea5ff4ef81b236bd6737821bccd63d5eb589b3c5278060ce89959174843d2",
          "sha256": "df99f17cb50fb7bc11c9f402f98d7ef326c87e6753c0a7bb8add8c58934ff8ec",
          "sha1": "903eefb6eab302617b0f01cc6d65664343bff2a7",
          "md5": "70bfde429862e7a8102386f6971e458d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-3.5.11-javadoc.jar",
          "url": "spring-boot-starter-validation-3.5.11-javadoc.jar",
          "size": 4769,
          "sha512": "b6309b741a29ee4c56422154060a727c854b263063d98bdab3ca27acb8b3d4aa5110602021dbef344d5baceafec7718aa210c4ff81ef77997dbb00117faee45c",
          "sha256": "b9f4580327eab1d05b77094ea964302dff3f45322f809153babe1e3f2d8ceeb3",
          "sha1": "a71fa31de390b655e07ad931e0e8fe8310a30f55",
          "md5": "a9487c1b21d8069eacd4ba95aea697e2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-3.5.11-sources.jar",
          "url": "spring-boot-starter-validation-3.5.11-sources.jar",
          "size": 4769,
          "sha512": "b6309b741a29ee4c56422154060a727c854b263063d98bdab3ca27acb8b3d4aa5110602021dbef344d5baceafec7718aa210c4ff81ef77997dbb00117faee45c",
          "sha256": "b9f4580327eab1d05b77094ea964302dff3f45322f809153babe1e3f2d8ceeb3",
          "sha1": "a71fa31de390b655e07ad931e0e8fe8310a30f55",
          "md5": "a9487c1b21d8069eacd4ba95aea697e2"
        }
      ]
    }
  ]
}
