{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-json",
    "version": "3.5.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.16"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.19.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.19.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.19.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-3.5.11.jar",
          "url": "spring-boot-starter-json-3.5.11.jar",
          "size": 4748,
          "sha512": "b616008396675946bbbbe4eb48895f7338b1206d1763bd669c7a2837c80740be5cbe1e71d9173a583e8201ecbc13b6e46a681a8d73884bc42ff94ed79b14be37",
          "sha256": "272f03677228c18884c795dcb8a0a3236fec2235d973c0fb9673737d97de0c32",
          "sha1": "4cdcd68dcddf0a4c645166e39c3fe448fe2b8e98",
          "md5": "206d103ea2dec78ddc0e4a499be8263b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.16"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.19.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.19.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.19.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-3.5.11.jar",
          "url": "spring-boot-starter-json-3.5.11.jar",
          "size": 4748,
          "sha512": "b616008396675946bbbbe4eb48895f7338b1206d1763bd669c7a2837c80740be5cbe1e71d9173a583e8201ecbc13b6e46a681a8d73884bc42ff94ed79b14be37",
          "sha256": "272f03677228c18884c795dcb8a0a3236fec2235d973c0fb9673737d97de0c32",
          "sha1": "4cdcd68dcddf0a4c645166e39c3fe448fe2b8e98",
          "md5": "206d103ea2dec78ddc0e4a499be8263b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.5.11-javadoc.jar",
          "url": "spring-boot-starter-json-3.5.11-javadoc.jar",
          "size": 4748,
          "sha512": "0f158383495ece64d0f1b2a9c5ce34e767d313b34ff22681efe8a42fc3866e86bb4a28cb540fbb887ef954c00c02a32e899da8f999228969769b8a91e3bf37f8",
          "sha256": "2b45d10aa84c55056f5e3f48e4a1ccf9594b35a5283f1cb36b5ee1e13c87654b",
          "sha1": "03f1420caf721d5962067b693675d4814adee40e",
          "md5": "9b4c9dff39fb6f8950fd61ec9bbcf09a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.5.11-sources.jar",
          "url": "spring-boot-starter-json-3.5.11-sources.jar",
          "size": 4748,
          "sha512": "0f158383495ece64d0f1b2a9c5ce34e767d313b34ff22681efe8a42fc3866e86bb4a28cb540fbb887ef954c00c02a32e899da8f999228969769b8a91e3bf37f8",
          "sha256": "2b45d10aa84c55056f5e3f48e4a1ccf9594b35a5283f1cb36b5ee1e13c87654b",
          "sha1": "03f1420caf721d5962067b693675d4814adee40e",
          "md5": "9b4c9dff39fb6f8950fd61ec9bbcf09a"
        }
      ]
    }
  ]
}
