{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.resilience4j",
    "module": "resilience4j-timelimiter",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-core",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "resilience4j-timelimiter-2.3.0.jar",
          "url": "resilience4j-timelimiter-2.3.0.jar",
          "size": 27410,
          "sha512": "7cb20173d0ed4ecc23deecac80451927def6e1bd346213f45cb3272f9825196d8f14199b4e4c3c6a360909611951df6be1759e7e588290efab4982a1aa9e1fc0",
          "sha256": "93f991fc710bfa4310a8a7713fabc48ceef64df119dc7d7cbadb38483a39a6c9",
          "sha1": "2de3016bd43ed1149ff1c035f1de11c9bbbec7fc",
          "md5": "44e07d069bec3d7ea97a802b1887eb8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-core",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "resilience4j-timelimiter-2.3.0.jar",
          "url": "resilience4j-timelimiter-2.3.0.jar",
          "size": 27410,
          "sha512": "7cb20173d0ed4ecc23deecac80451927def6e1bd346213f45cb3272f9825196d8f14199b4e4c3c6a360909611951df6be1759e7e588290efab4982a1aa9e1fc0",
          "sha256": "93f991fc710bfa4310a8a7713fabc48ceef64df119dc7d7cbadb38483a39a6c9",
          "sha1": "2de3016bd43ed1149ff1c035f1de11c9bbbec7fc",
          "md5": "44e07d069bec3d7ea97a802b1887eb8a"
        }
      ]
    }
  ]
}
