{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "3.5.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.52"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.52"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.52"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.5.11.jar",
          "url": "spring-boot-starter-tomcat-3.5.11.jar",
          "size": 4794,
          "sha512": "f23f72a5110ed300225e6f21fe7ab3e57ac4d4ef06f1c04fb537da39dd4585f5d2ba957bace57775c3cdcb25bf89576765e0954b66c73ceba9b4c8f42d5aab27",
          "sha256": "3b14b88ca09ff19a99dbe84ebc434eebd25ac5515d3c712106fe41330716dbca",
          "sha1": "fb7b96cb61e5fd5700aed96194562e32d166b5ef",
          "md5": "f0b56b496109b6a2eafbee39df9e7747"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.52"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.52"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.52"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.5.11.jar",
          "url": "spring-boot-starter-tomcat-3.5.11.jar",
          "size": 4794,
          "sha512": "f23f72a5110ed300225e6f21fe7ab3e57ac4d4ef06f1c04fb537da39dd4585f5d2ba957bace57775c3cdcb25bf89576765e0954b66c73ceba9b4c8f42d5aab27",
          "sha256": "3b14b88ca09ff19a99dbe84ebc434eebd25ac5515d3c712106fe41330716dbca",
          "sha1": "fb7b96cb61e5fd5700aed96194562e32d166b5ef",
          "md5": "f0b56b496109b6a2eafbee39df9e7747"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.5.11-javadoc.jar",
          "url": "spring-boot-starter-tomcat-3.5.11-javadoc.jar",
          "size": 4794,
          "sha512": "eb29ead4b767d110970ae3aabf20ea87b73b45e6762a7dfa675a8fc56de74f9e39267b081458fe9f1bb3341ecca640f30075ecff35eb164b643d85bd0ee7cc6d",
          "sha256": "4914751bba5c4f0940c76f308b675aa32ab9dac283d4aee30f083ba31094f97a",
          "sha1": "d2b064d801c7ec74620332a148be3c70971006ac",
          "md5": "7ddf0bdb9ee8f19864ba04f39fd5d009"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.5.11-sources.jar",
          "url": "spring-boot-starter-tomcat-3.5.11-sources.jar",
          "size": 4794,
          "sha512": "4e442845fda2973abc8fa489fac0fb044e21d1a1a731d0334c54b89c57d6c419d02ac2a1699b974a8a5f65718011eef3f912d728b915076679ae3a9d17d93fda",
          "sha256": "4a42a86902be904de1ab5959e50e553992a0c92c7ca0b618042ac20d02605761",
          "sha1": "ee6558de1a445be6504ba3dc812589812ae29c65",
          "md5": "6d13856620a953013b1bf69e22829b37"
        }
      ]
    }
  ]
}
