{
  "formatVersion": "1.1",
  "component": {
    "group": "io.projectreactor",
    "module": "reactor-core",
    "version": "3.7.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-core-3.7.16.jar",
          "url": "reactor-core-3.7.16.jar",
          "size": 1897778,
          "sha512": "f0313eedd03acee06e7e38a915ecb8060d6996ffafbd05afeff4c7cdeb239e022b65f8f721290e228d5c30180d069a417cb40c3f782b643508fa0b64d11de10f",
          "sha256": "1b22531e50a243d486b9a9f95bf21b4ddb0d0ebcae4e02584a91912d1dec5a0c",
          "sha1": "dc7f2ba3c4fbc69678937dfe1ad45264d8a1c7be",
          "md5": "16e2232870bc51f359c0de6e2d924e64"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-core-3.7.16.jar",
          "url": "reactor-core-3.7.16.jar",
          "size": 1897778,
          "sha512": "f0313eedd03acee06e7e38a915ecb8060d6996ffafbd05afeff4c7cdeb239e022b65f8f721290e228d5c30180d069a417cb40c3f782b643508fa0b64d11de10f",
          "sha256": "1b22531e50a243d486b9a9f95bf21b4ddb0d0ebcae4e02584a91912d1dec5a0c",
          "sha1": "dc7f2ba3c4fbc69678937dfe1ad45264d8a1c7be",
          "md5": "16e2232870bc51f359c0de6e2d924e64"
        }
      ]
    }
  ]
}
