{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.resilience4j",
    "module": "resilience4j-spring6",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-annotations",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-consumer",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-framework-common",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "resilience4j-spring6-2.3.0.jar",
          "url": "resilience4j-spring6-2.3.0.jar",
          "size": 143331,
          "sha512": "0a66ddea3aa26851e52a629f2a4b89d50395845ecf0ebe36730583e53c30f4c8c439f155625982bc0522de7a548813af7dd1688721e78bd28c012646f8e412ee",
          "sha256": "7c6d46fe45309096b1abf4024785cec64c92cd88d5129f00f97539269ba0349c",
          "sha1": "2ed6c1cc76fd03c97c768ff4f2a525a3ef7819bf",
          "md5": "54cf12ba8606b784ea871ffbdcf20a0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-annotations",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-consumer",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-framework-common",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "resilience4j-spring6-2.3.0.jar",
          "url": "resilience4j-spring6-2.3.0.jar",
          "size": 143331,
          "sha512": "0a66ddea3aa26851e52a629f2a4b89d50395845ecf0ebe36730583e53c30f4c8c439f155625982bc0522de7a548813af7dd1688721e78bd28c012646f8e412ee",
          "sha256": "7c6d46fe45309096b1abf4024785cec64c92cd88d5129f00f97539269ba0349c",
          "sha1": "2ed6c1cc76fd03c97c768ff4f2a525a3ef7819bf",
          "md5": "54cf12ba8606b784ea871ffbdcf20a0b"
        }
      ]
    }
  ]
}
