{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-messaging",
    "version": "6.2.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-messaging-6.2.16.jar",
          "url": "spring-messaging-6.2.16.jar",
          "size": 618636,
          "sha512": "223ace3028909f67baa43b3e983cd80812cd165969f330f3b763255a324d7031cd527d3724b945cb571b06a656efec2bae7530b4e875230fdc2278149d667701",
          "sha256": "b1a39ad392065b40223e5405d498f5661de353f58230d733d4febad7b36c5d79",
          "sha1": "54c6aea32d934323aa3b370e79bafebf646e5ffa",
          "md5": "2aa124c8f869c460191d5dfd01a5fc10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-messaging-6.2.16.jar",
          "url": "spring-messaging-6.2.16.jar",
          "size": 618636,
          "sha512": "223ace3028909f67baa43b3e983cd80812cd165969f330f3b763255a324d7031cd527d3724b945cb571b06a656efec2bae7530b4e875230fdc2278149d667701",
          "sha256": "b1a39ad392065b40223e5405d498f5661de353f58230d733d4febad7b36c5d79",
          "sha1": "54c6aea32d934323aa3b370e79bafebf646e5ffa",
          "md5": "2aa124c8f869c460191d5dfd01a5fc10"
        }
      ]
    }
  ]
}
