{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.cloud.tools",
    "module": "jib-gradle-plugin",
    "version": "3.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.2",
      "buildId": "e4vd3542gffbrb75kknio67vtq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jib-gradle-plugin-3.4.5.jar",
          "url": "jib-gradle-plugin-3.4.5.jar",
          "size": 560458,
          "sha512": "02cc0c69b51c39a1b396dc2a8db10e76532fdae281036cdceb1ee47222454c4595dc5cb3b72806692919a520255d3dbea03dd8a4d9b9415fe2b9cbff70aa8ad6",
          "sha256": "5b6b8443e45a021f024086108c2d5b0fdf51a1650f78ec731869fc36d06306a4",
          "sha1": "1157026ec0d903cfca991d3c260a7b4c5d4aeb1c",
          "md5": "7477c92319daabb6f68b5f1a7c05fb6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.http-client",
          "module": "google-http-client",
          "version": {
            "requires": "1.42.2"
          }
        },
        {
          "group": "com.google.http-client",
          "module": "google-http-client-apache-v2",
          "version": {
            "requires": "1.42.2"
          }
        },
        {
          "group": "com.google.auth",
          "module": "google-auth-library-oauth2-http",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.26.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.2-jre"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "com.google.cloud.tools",
          "module": "jib-build-plan",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.google.cloud.tools",
          "module": "jib-plugins-extension-common",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.cloud.tools",
          "module": "jib-gradle-plugin-extension-api",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "jib-gradle-plugin-3.4.5.jar",
          "url": "jib-gradle-plugin-3.4.5.jar",
          "size": 560458,
          "sha512": "02cc0c69b51c39a1b396dc2a8db10e76532fdae281036cdceb1ee47222454c4595dc5cb3b72806692919a520255d3dbea03dd8a4d9b9415fe2b9cbff70aa8ad6",
          "sha256": "5b6b8443e45a021f024086108c2d5b0fdf51a1650f78ec731869fc36d06306a4",
          "sha1": "1157026ec0d903cfca991d3c260a7b4c5d4aeb1c",
          "md5": "7477c92319daabb6f68b5f1a7c05fb6b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jib-gradle-plugin-3.4.5-javadoc.jar",
          "url": "jib-gradle-plugin-3.4.5-javadoc.jar",
          "size": 413892,
          "sha512": "236d5c5d784361ebf3f6ecc4ff96d2e45331698840a9024b757257f3b22f66b107318796d1e5c1992162210075317afc1164996fcf243650b522e6efa23f3a4c",
          "sha256": "6502f74f104e6b7fe01eaab8dde46cb4a932f87164c6bb894aa9a5bf639105d6",
          "sha1": "f24e8f2e4d4c83c55c160ee6a5af505ac1f085ba",
          "md5": "98f7ec879f1159336d70dbd17b690aac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jib-gradle-plugin-3.4.5-sources.jar",
          "url": "jib-gradle-plugin-3.4.5-sources.jar",
          "size": 53035,
          "sha512": "8cb300558f716137bc327cd18e157edaa4fe561882b31d33c5d9b25e24bf5eee2f4dad93460e430d1ce2b8ce3ae3f5a7ffc5d59010ac6a4354fc0792d441b0a0",
          "sha256": "2ef70f57baa4a0e707a1eabcb6e1be0ec8f5f1f3114269cedfaedc0652cc7469",
          "sha1": "393a859dd3f44f40b457c450907b51b52a3f9abe",
          "md5": "41a79493308421027f42aeba6d272a99"
        }
      ]
    }
  ]
}
