{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.resilience4j",
    "module": "resilience4j-retry",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-core",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "resilience4j-retry-2.3.0.jar",
          "url": "resilience4j-retry-2.3.0.jar",
          "size": 49846,
          "sha512": "9735437a83d34420138686ece810247644f68b067473eb4bc0dab51307f91db4dc8c898138efb2a9e05ebd6696f12a9c9d0b3a6e17ca6bbe669ca192b3e21481",
          "sha256": "0020f75c269706a796e4b9d7e85c31acc0ab4e2776fd8e56f571c3fe204333fa",
          "sha1": "1953682ce8b7e69ff5a02d3772ef9c932f2bab3e",
          "md5": "90e38e550fe95bb2e1d5a1248238ba69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-core",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "resilience4j-retry-2.3.0.jar",
          "url": "resilience4j-retry-2.3.0.jar",
          "size": 49846,
          "sha512": "9735437a83d34420138686ece810247644f68b067473eb4bc0dab51307f91db4dc8c898138efb2a9e05ebd6696f12a9c9d0b3a6e17ca6bbe669ca192b3e21481",
          "sha256": "0020f75c269706a796e4b9d7e85c31acc0ab4e2776fd8e56f571c3fe204333fa",
          "sha1": "1953682ce8b7e69ff5a02d3772ef9c932f2bab3e",
          "md5": "90e38e550fe95bb2e1d5a1248238ba69"
        }
      ]
    }
  ]
}
