{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-autoconfigure",
    "version": "3.5.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.5.11.jar",
          "url": "spring-boot-autoconfigure-3.5.11.jar",
          "size": 2085969,
          "sha512": "53b5db869925823961b46b7b56bd0b424a41fe4d021392a284455c8d1e06da5f9a7b97f88b2b6abd92b8efe9c82ba62b853a7fd3d3d9bc38e1baadea20509030",
          "sha256": "1bfb60bb35836b72119335fc575a91dcc2984ba4f7214deebb4ee8e44eb51efa",
          "sha1": "3c7d2ec2ac3c301e95814e37fed1c86c19927fc4",
          "md5": "1810e7a0891561a85363d697d9dfa9ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.5.11.jar",
          "url": "spring-boot-autoconfigure-3.5.11.jar",
          "size": 2085969,
          "sha512": "53b5db869925823961b46b7b56bd0b424a41fe4d021392a284455c8d1e06da5f9a7b97f88b2b6abd92b8efe9c82ba62b853a7fd3d3d9bc38e1baadea20509030",
          "sha256": "1bfb60bb35836b72119335fc575a91dcc2984ba4f7214deebb4ee8e44eb51efa",
          "sha1": "3c7d2ec2ac3c301e95814e37fed1c86c19927fc4",
          "md5": "1810e7a0891561a85363d697d9dfa9ec"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.5.11-javadoc.jar",
          "url": "spring-boot-autoconfigure-3.5.11-javadoc.jar",
          "size": 3201124,
          "sha512": "edbbbcfb2e2591aa3da4e505e8a75caae816b09b6a8b52649d33001454e7fdc19d9c733f7cc34906ea49537a638272779090f4e44a281b4a2cef476c7b899c8c",
          "sha256": "7f8c3ed3ddebecf78071ce4fef30bd881730e0cc6d4b0bab938e30815c885908",
          "sha1": "c80abfc014b29508e58f7fdfa897e261f13c4b13",
          "md5": "0e40bb04b7d1e335549d632d148614c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.5.11-sources.jar",
          "url": "spring-boot-autoconfigure-3.5.11-sources.jar",
          "size": 1191333,
          "sha512": "9332d9c6c264911fb6d194bf03e26036361d6760edd885c143167924eafb225abd95d788d2f2bebd02eae97a31831640d65e0cb16fad8deb0713e35552d1afe2",
          "sha256": "deb0613599fb5ef4f03d94402c39bde162f5d4bcd56b28410e9f0c4a57c483c3",
          "sha1": "f70583cb712513be410b15a02e7bf0c9557cbd55",
          "md5": "de29f95d5323c12b6f50afe6e86f2441"
        }
      ]
    }
  ]
}
