{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-actuator",
    "version": "3.5.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-3.5.11.jar",
          "url": "spring-boot-actuator-3.5.11.jar",
          "size": 703707,
          "sha512": "36a2eb664e50b5b29a7cf6013e807ef08f83b2e41f1e86d545a69d47006bfd5aac688a23a646f1300ae1cb9aa01855781bea47dae61a2cfd20d88132f436edda",
          "sha256": "f59b2fe37b663fc17d33c0bd093b366c857392851d24be16323b3b7626ff28ab",
          "sha1": "09bf6a5015a39eb539e60d8f6e4879ad59da0ae7",
          "md5": "3d3b65f229a1d44d960e0ae898dd7079"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-3.5.11.jar",
          "url": "spring-boot-actuator-3.5.11.jar",
          "size": 703707,
          "sha512": "36a2eb664e50b5b29a7cf6013e807ef08f83b2e41f1e86d545a69d47006bfd5aac688a23a646f1300ae1cb9aa01855781bea47dae61a2cfd20d88132f436edda",
          "sha256": "f59b2fe37b663fc17d33c0bd093b366c857392851d24be16323b3b7626ff28ab",
          "sha1": "09bf6a5015a39eb539e60d8f6e4879ad59da0ae7",
          "md5": "3d3b65f229a1d44d960e0ae898dd7079"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-3.5.11-javadoc.jar",
          "url": "spring-boot-actuator-3.5.11-javadoc.jar",
          "size": 1507164,
          "sha512": "616083a31d7287c38dff08e17bc8033b95d9591546a7e55427c1d4a9433558222d524b800e8d88a8aed57e89fcb527704aa45295ebda55443df746845dd22333",
          "sha256": "fc1d1f0b747122ef6b1b0dd9029a7b69bc7a1652197c47084ed5fb1f6a002be6",
          "sha1": "4ffe37282f2d8092332fa835c246d0a32466d7f1",
          "md5": "63217f74a2ccebd3910941b4c8e2a9e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-3.5.11-sources.jar",
          "url": "spring-boot-actuator-3.5.11-sources.jar",
          "size": 470869,
          "sha512": "a0c2c405d38a67bb186bd62d2c4fe9eaeb0979cabebb005f10719fd2503e316b6a6249591dca73b40b60a5734dd28e73abb861b39635b4abe861adc3493f461a",
          "sha256": "4b6bcf42f2f4f2dae7fd274eb446e771fdb3f78bb1382b918e68dc87bab0d587",
          "sha1": "a3a5fbef170b0d058f9a1890eb347802aeea94b9",
          "md5": "13ec4d2eda0ba3b83ef2f7fbd097f360"
        }
      ]
    }
  ]
}
