{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.resilience4j",
    "module": "resilience4j-consumer",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "resilience4j-consumer-2.3.0.jar",
          "url": "resilience4j-consumer-2.3.0.jar",
          "size": 8308,
          "sha512": "c7d4e43efe5580acc09a8bac0b1c07cfd728c6e2a2fcfcdcddf90e06028c8a96af3008da94150467d298ab09c1277e13fe94ad9f319cb66f76be6894b647050c",
          "sha256": "be6e02a9e5b47514a37fd9f8105b0ad42325c5ea8b7d74a75afe3c0d534ffe10",
          "sha1": "5649b6e0db11eb78e4a07ba08575d23301c1993a",
          "md5": "081eb9a45730f3da6f9dd0cb7866f6d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-core",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-circularbuffer",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "resilience4j-consumer-2.3.0.jar",
          "url": "resilience4j-consumer-2.3.0.jar",
          "size": 8308,
          "sha512": "c7d4e43efe5580acc09a8bac0b1c07cfd728c6e2a2fcfcdcddf90e06028c8a96af3008da94150467d298ab09c1277e13fe94ad9f319cb66f76be6894b647050c",
          "sha256": "be6e02a9e5b47514a37fd9f8105b0ad42325c5ea8b7d74a75afe3c0d534ffe10",
          "sha1": "5649b6e0db11eb78e4a07ba08575d23301c1993a",
          "md5": "081eb9a45730f3da6f9dd0cb7866f6d7"
        }
      ]
    }
  ]
}
