{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.resilience4j",
    "module": "resilience4j-spring-boot3",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-spring6",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "resilience4j-spring-boot3-2.3.0.jar",
          "url": "resilience4j-spring-boot3-2.3.0.jar",
          "size": 105223,
          "sha512": "7666f8ed5ec42ea143941485a0063d587b6043ec43cf028727c01fd58be5b5af9e9b913d42e19e507c330aa37e60cb3b2c717d3f19c8e78309aa08a9970e5156",
          "sha256": "510c5d5d618def88482053d4c2fcf286a21ee95ef2d249020f028c94895f6b2e",
          "sha1": "81c5c03cd43c99c588d82dcef3b20e6861addc99",
          "md5": "78e8d0b61457859110eeb176c80f0a9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-micrometer",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-spring6",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "resilience4j-spring-boot3-2.3.0.jar",
          "url": "resilience4j-spring-boot3-2.3.0.jar",
          "size": 105223,
          "sha512": "7666f8ed5ec42ea143941485a0063d587b6043ec43cf028727c01fd58be5b5af9e9b913d42e19e507c330aa37e60cb3b2c717d3f19c8e78309aa08a9970e5156",
          "sha256": "510c5d5d618def88482053d4c2fcf286a21ee95ef2d249020f028c94895f6b2e",
          "sha1": "81c5c03cd43c99c588d82dcef3b20e6861addc99",
          "md5": "78e8d0b61457859110eeb176c80f0a9e"
        }
      ]
    }
  ]
}
