{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.resilience4j",
    "module": "resilience4j-core",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "resilience4j-core-2.3.0.jar",
          "url": "resilience4j-core-2.3.0.jar",
          "size": 91257,
          "sha512": "d9fc287e9de2b6fbec54e119b30ea8f903d43fea8edbc10fa8e9732e09bcd8efa0fe08123c5cf559cd08da416d3226577816d4caaccc013995cc293224d1ff81",
          "sha256": "bdaf2c553265b9c1ac6967acf598e3f433cc592e85e7872bd24d1e6264a97b93",
          "sha1": "04df5e76f2e2b15db6971d5102ffa9b494e38cfe",
          "md5": "8a1db78c7c9b214531f24e89b0ac9837"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "resilience4j-core-2.3.0.jar",
          "url": "resilience4j-core-2.3.0.jar",
          "size": 91257,
          "sha512": "d9fc287e9de2b6fbec54e119b30ea8f903d43fea8edbc10fa8e9732e09bcd8efa0fe08123c5cf559cd08da416d3226577816d4caaccc013995cc293224d1ff81",
          "sha256": "bdaf2c553265b9c1ac6967acf598e3f433cc592e85e7872bd24d1e6264a97b93",
          "sha1": "04df5e76f2e2b15db6971d5102ffa9b494e38cfe",
          "md5": "8a1db78c7c9b214531f24e89b0ac9837"
        }
      ]
    }
  ]
}
