{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-buildpack-platform",
    "version": "3.5.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.5.11.jar",
          "url": "spring-boot-buildpack-platform-3.5.11.jar",
          "size": 323305,
          "sha512": "8cbd10162b9933b229b26d1a473021a9f02f426df54de29f28bfb48dccffc0145763430da91820bbbd89403c4fda230d7bb4f58c0d89c55beb845b21b4396e49",
          "sha256": "fa710c25491041492c98ade22f3e2c9428378cb4d8bf0d326df507ec9bda0372",
          "sha1": "f356b9221f4bd1aa155fe522633e9518f3aff99f",
          "md5": "691b96ddf1e26816736c3c3e9306c140"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.19.4"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.5.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.16"
          }
        },
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.5.11.jar",
          "url": "spring-boot-buildpack-platform-3.5.11.jar",
          "size": 323305,
          "sha512": "8cbd10162b9933b229b26d1a473021a9f02f426df54de29f28bfb48dccffc0145763430da91820bbbd89403c4fda230d7bb4f58c0d89c55beb845b21b4396e49",
          "sha256": "fa710c25491041492c98ade22f3e2c9428378cb4d8bf0d326df507ec9bda0372",
          "sha1": "f356b9221f4bd1aa155fe522633e9518f3aff99f",
          "md5": "691b96ddf1e26816736c3c3e9306c140"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.5.11-javadoc.jar",
          "url": "spring-boot-buildpack-platform-3.5.11-javadoc.jar",
          "size": 453471,
          "sha512": "7098dc0fa22f05fed7b8bb37332f72d9356681b35d583d6182ef275425362862e3cdbbdb3910ff49ce0465fda736ac525ee0d43fa24c420d901955c56cb4162d",
          "sha256": "788b276d3135eb04bf07f3bb5519786f4d1ba5426ac0b6f65f0abb299509eafe",
          "sha1": "c8bbc818660cd6f460adf5cfb87a83d1e5c70d91",
          "md5": "4d1a8b974dda5f6d970929ceaa041539"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.5.11-sources.jar",
          "url": "spring-boot-buildpack-platform-3.5.11-sources.jar",
          "size": 193049,
          "sha512": "65552394d7e9677d1baab52fb6fad86b28277cb3d385af82e459d7704e80b59739b6bd3c1b0fc12fd97a0476371f3a123f2a82cb88eccaf599a2edb607822883",
          "sha256": "d5eaa9a7b6fb950cb6a5cc4df7b5cc03a86cedc46d6675731513523f0479c3aa",
          "sha1": "b42d9ae74fdbdc6058024150bb4e07ec65eb391b",
          "md5": "8f614624ced7b25907b643da488e3f71"
        }
      ]
    }
  ]
}
