{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-actuator-autoconfigure",
    "version": "3.5.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.5.11"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator",
          "version": {
            "requires": "3.5.11"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-3.5.11.jar",
          "url": "spring-boot-actuator-autoconfigure-3.5.11.jar",
          "size": 842900,
          "sha512": "a57e9e791e482d35ba073458ae2b8207f07be86e3b4ef3a0b70bdf9cab42bd89f31111798246d91b59fd281b8e8723f667c7d6a7f85d85db74785930fcd45c05",
          "sha256": "7a30bd6c75553553e4e724f519d1e18bee6072da509ef0ebe70e20e469f9891c",
          "sha1": "f77599c9b35411af19467d1b8efad81436e7510e",
          "md5": "072390b7f0be6d37883b60d33614f185"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.19.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.5.11"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator",
          "version": {
            "requires": "3.5.11"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-3.5.11.jar",
          "url": "spring-boot-actuator-autoconfigure-3.5.11.jar",
          "size": 842900,
          "sha512": "a57e9e791e482d35ba073458ae2b8207f07be86e3b4ef3a0b70bdf9cab42bd89f31111798246d91b59fd281b8e8723f667c7d6a7f85d85db74785930fcd45c05",
          "sha256": "7a30bd6c75553553e4e724f519d1e18bee6072da509ef0ebe70e20e469f9891c",
          "sha1": "f77599c9b35411af19467d1b8efad81436e7510e",
          "md5": "072390b7f0be6d37883b60d33614f185"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-3.5.11-javadoc.jar",
          "url": "spring-boot-actuator-autoconfigure-3.5.11-javadoc.jar",
          "size": 1462533,
          "sha512": "eeac52a75942fa8cf56f7598edf6ebf989c29020a3d8e84679e78485070d9a21c5e9c5ba8518e1b16ed971078eb959db84aef34c73d3a98b72bf79912fe564ad",
          "sha256": "2e9f0929fa8de084f8343d3e3f99381b0fa099ded4f89f8b5a4439f310315cbf",
          "sha1": "0360bb621316a91557ec5200d15045bb405ca12d",
          "md5": "06cd9bb043e1e9ad9845c5869cc0986f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-3.5.11-sources.jar",
          "url": "spring-boot-actuator-autoconfigure-3.5.11-sources.jar",
          "size": 578180,
          "sha512": "a1dbb6652fd25fc1127e29881f81fabe1fafcbcc6df7ea0a17fe7fed341be55951dba8ede8ac41f97363db5c7d022257852559353bf19626de67eede324b4b5e",
          "sha256": "a760d2c8dd84523e813645c5811b7503487cc8ed2bdcb8a978ca73d2632d5923",
          "sha1": "8f7c977b6add7ea941a880d95422b6526d7e5261",
          "md5": "6659f788d07d38a61a823c8c8de41be2"
        }
      ]
    }
  ]
}
