{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-oxm",
    "version": "6.2.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-oxm-6.2.16.jar",
          "url": "spring-oxm-6.2.16.jar",
          "size": 59857,
          "sha512": "8695fc4913e1f74fdfa3ad73fcb889e6cdf9ecb379050b9b4d920467e5dc4cd26c38ef76f9b45755710864b796f04271a3c9848590b561eedd5239fedb2a998c",
          "sha256": "9daa0b6d05a0b8c7901b746f4b0cb10792c119d04e34765501c5ca9ba3e6bfea",
          "sha1": "7f476dfb8eae04834641304db493032738ab5ca7",
          "md5": "2c1bd6ce99331a17596da932b53332f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-oxm-6.2.16.jar",
          "url": "spring-oxm-6.2.16.jar",
          "size": 59857,
          "sha512": "8695fc4913e1f74fdfa3ad73fcb889e6cdf9ecb379050b9b4d920467e5dc4cd26c38ef76f9b45755710864b796f04271a3c9848590b561eedd5239fedb2a998c",
          "sha256": "9daa0b6d05a0b8c7901b746f4b0cb10792c119d04e34765501c5ca9ba3e6bfea",
          "sha1": "7f476dfb8eae04834641304db493032738ab5ca7",
          "md5": "2c1bd6ce99331a17596da932b53332f1"
        }
      ]
    }
  ]
}
