{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.kafka",
    "module": "spring-kafka",
    "version": "3.3.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "6.2.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.2.16"
          }
        },
        {
          "group": "org.springframework.retry",
          "module": "spring-retry",
          "version": {
            "requires": "2.0.12"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.14.14"
          }
        }
      ],
      "files": [
        {
          "name": "spring-kafka-3.3.13.jar",
          "url": "spring-kafka-3.3.13.jar",
          "size": 880071,
          "sha512": "7917b268eb7b6a9c6e08a9935c15ca6b60d5b69b19d6969447e402e55215520ea95628aba63505044270ae25ef2c78c5a0c26df2d6929b1682a552edf55ca576",
          "sha256": "ad286d5d011ee4ce8b18d6673c2c31ef1021034faba9c71b4692f74a1f4b8092",
          "sha1": "e8dec3dec5d0f9889b8091506d2d29b06d751c25",
          "md5": "f132751ba1dae998b8cd80b65c5e03a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "6.2.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.2.16"
          }
        },
        {
          "group": "org.springframework.retry",
          "module": "spring-retry",
          "version": {
            "requires": "2.0.12"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.14.14"
          }
        }
      ],
      "files": [
        {
          "name": "spring-kafka-3.3.13.jar",
          "url": "spring-kafka-3.3.13.jar",
          "size": 880071,
          "sha512": "7917b268eb7b6a9c6e08a9935c15ca6b60d5b69b19d6969447e402e55215520ea95628aba63505044270ae25ef2c78c5a0c26df2d6929b1682a552edf55ca576",
          "sha256": "ad286d5d011ee4ce8b18d6673c2c31ef1021034faba9c71b4692f74a1f4b8092",
          "sha1": "e8dec3dec5d0f9889b8091506d2d29b06d751c25",
          "md5": "f132751ba1dae998b8cd80b65c5e03a3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-kafka-3.3.13-javadoc.jar",
          "url": "spring-kafka-3.3.13-javadoc.jar",
          "size": 1645797,
          "sha512": "f8cc3c71fcc6c627eb6cf91b6ba9af7d631fdbfd65ed37ea369c81e9bde816f86a7447ec141f311469ec30d4e022432c8424358cef75f631742c3016fb943aaa",
          "sha256": "fb8d438a55372dd2d0a785fc3e724d8b6ba4c812199e604590a1dc05bbfb87bd",
          "sha1": "7b12a4cdda01036f2b0ac93f6fff358d506bd40a",
          "md5": "a53ed8085fbb3e06f073ddcee3f59a30"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-kafka-3.3.13-sources.jar",
          "url": "spring-kafka-3.3.13-sources.jar",
          "size": 587149,
          "sha512": "fa0a6ca71b592a2d61fb16ba0aa84e1bd1f2800945bb97c53ca0c45abc97aa38174aee2993b204aa5c72254f3f62ea2a62063bf0cd25239544790d3bb08f3045",
          "sha256": "c4a54b68bf8fe61326f51e1262ba9a05fe168c2cfdc2ce6dd317806f96c0f22c",
          "sha1": "8ed13798fb11cff8e2b28754b267b57c23801d63",
          "md5": "6f8f85db7baeaa6e16be8ddbcd257bad"
        }
      ]
    },
    {
      "name": "optionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-streams",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.18.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.18.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-joda",
          "version": {
            "requires": "2.18.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.18.5"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "3.4.13"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            },
            {
              "group": "io.micrometer",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.7.16"
          }
        },
        {
          "group": "io.projectreactor.kafka",
          "module": "reactor-kafka",
          "version": {
            "requires": "1.3.25"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.14.14"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-tracing",
          "version": {
            "requires": "1.4.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-kafka-3.3.13.jar",
          "url": "spring-kafka-3.3.13.jar",
          "size": 880071,
          "sha512": "7917b268eb7b6a9c6e08a9935c15ca6b60d5b69b19d6969447e402e55215520ea95628aba63505044270ae25ef2c78c5a0c26df2d6929b1682a552edf55ca576",
          "sha256": "ad286d5d011ee4ce8b18d6673c2c31ef1021034faba9c71b4692f74a1f4b8092",
          "sha1": "e8dec3dec5d0f9889b8091506d2d29b06d751c25",
          "md5": "f132751ba1dae998b8cd80b65c5e03a3"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.kafka",
          "name": "spring-kafka-optional",
          "version": "3.3.13"
        }
      ]
    },
    {
      "name": "optionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-streams",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.18.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.18.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-joda",
          "version": {
            "requires": "2.18.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.18.5"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "3.4.13"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            },
            {
              "group": "io.micrometer",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.7.16"
          }
        },
        {
          "group": "io.projectreactor.kafka",
          "module": "reactor-kafka",
          "version": {
            "requires": "1.3.25"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.14.14"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-tracing",
          "version": {
            "requires": "1.4.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-kafka-3.3.13.jar",
          "url": "spring-kafka-3.3.13.jar",
          "size": 880071,
          "sha512": "7917b268eb7b6a9c6e08a9935c15ca6b60d5b69b19d6969447e402e55215520ea95628aba63505044270ae25ef2c78c5a0c26df2d6929b1682a552edf55ca576",
          "sha256": "ad286d5d011ee4ce8b18d6673c2c31ef1021034faba9c71b4692f74a1f4b8092",
          "sha1": "e8dec3dec5d0f9889b8091506d2d29b06d751c25",
          "md5": "f132751ba1dae998b8cd80b65c5e03a3"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.kafka",
          "name": "spring-kafka-optional",
          "version": "3.3.13"
        }
      ]
    }
  ]
}
