{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-logging",
    "version": "3.5.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.24.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.5.11.jar",
          "url": "spring-boot-starter-logging-3.5.11.jar",
          "size": 4761,
          "sha512": "6649a33be74c915decffea6be398d8f76b3dd532590485faa59d90777b8844b1e349867ad8dec68bca860d286d215230c131d08368f2ab611c5cd06841a52afd",
          "sha256": "5fffb9db8fd10f16f8721a2925d13a145ee0a8e9b91749c3a42f1bb6e892ade1",
          "sha1": "62b692ed7aee31a5670796be8b07732b6b836f4e",
          "md5": "2b581addba949db13998e332f8cbc84d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.32"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.24.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.5.11.jar",
          "url": "spring-boot-starter-logging-3.5.11.jar",
          "size": 4761,
          "sha512": "6649a33be74c915decffea6be398d8f76b3dd532590485faa59d90777b8844b1e349867ad8dec68bca860d286d215230c131d08368f2ab611c5cd06841a52afd",
          "sha256": "5fffb9db8fd10f16f8721a2925d13a145ee0a8e9b91749c3a42f1bb6e892ade1",
          "sha1": "62b692ed7aee31a5670796be8b07732b6b836f4e",
          "md5": "2b581addba949db13998e332f8cbc84d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.5.11-javadoc.jar",
          "url": "spring-boot-starter-logging-3.5.11-javadoc.jar",
          "size": 4761,
          "sha512": "3ae58fe76d9d8d93ad2026d6167f4cc83baf9907c48bd252616245eb5fbb4d851e50f7f17aec53ee2925e0d25f5e32cec9da1dc6277e9cff630e79d9215a14c3",
          "sha256": "ea48848c61c7e01051e65b2362bc64be34a54bd9636d7e287cc9c8c7b16cf899",
          "sha1": "3d93d1a46a256690fabc99ab014e34d5d3ead14b",
          "md5": "69f9b93540f78e27ae3d83b67ae4192d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.5.11-sources.jar",
          "url": "spring-boot-starter-logging-3.5.11-sources.jar",
          "size": 4761,
          "sha512": "3ae58fe76d9d8d93ad2026d6167f4cc83baf9907c48bd252616245eb5fbb4d851e50f7f17aec53ee2925e0d25f5e32cec9da1dc6277e9cff630e79d9215a14c3",
          "sha256": "ea48848c61c7e01051e65b2362bc64be34a54bd9636d7e287cc9c8c7b16cf899",
          "sha1": "3d93d1a46a256690fabc99ab014e34d5d3ead14b",
          "md5": "69f9b93540f78e27ae3d83b67ae4192d"
        }
      ]
    }
  ]
}
