{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.resilience4j",
    "module": "resilience4j-micrometer",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "resilience4j-micrometer-2.3.0.jar",
          "url": "resilience4j-micrometer-2.3.0.jar",
          "size": 76505,
          "sha512": "8024c6a1101b67eb06415b8514ae461cb475817c28e3c57d70443e766bc5dcc5cadf511d1d6b7375039846c0a40d3c707eca7093dc0230a8f0f8804674ad172d",
          "sha256": "fecb499507e27fc7b4183e1218444150a6a399659c5b1e09ce48dfad8bae79cf",
          "sha1": "79fbfe7fc77683bc0ecba5bfeb73709d5e0759ad",
          "md5": "a529138587f654b68d6ccb14df5dc9dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-bulkhead",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-circuitbreaker",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-retry",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-ratelimiter",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-timelimiter",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "resilience4j-micrometer-2.3.0.jar",
          "url": "resilience4j-micrometer-2.3.0.jar",
          "size": 76505,
          "sha512": "8024c6a1101b67eb06415b8514ae461cb475817c28e3c57d70443e766bc5dcc5cadf511d1d6b7375039846c0a40d3c707eca7093dc0230a8f0f8804674ad172d",
          "sha256": "fecb499507e27fc7b4183e1218444150a6a399659c5b1e09ce48dfad8bae79cf",
          "sha1": "79fbfe7fc77683bc0ecba5bfeb73709d5e0759ad",
          "md5": "a529138587f654b68d6ccb14df5dc9dd"
        }
      ]
    }
  ]
}
