{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-context-support",
    "version": "6.2.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-support-6.2.16.jar",
          "url": "spring-context-support-6.2.16.jar",
          "size": 175412,
          "sha512": "bbf213bcfd41f92e5d0e2ee16f762dd4609584252c63e0e0139674359846ed42b5484b7cf5ed8259532c9988b08560ff91044c1d0e4fb0b035d824b9c06eace1",
          "sha256": "d292ddb7eb99eda8adddd9c818a69bb06d39b50405473e9fded7dd268183175c",
          "sha1": "5894b963f121c50c606cb34c4fc876bb4394772c",
          "md5": "eae900ff12246dde95c07857050715a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-support-6.2.16.jar",
          "url": "spring-context-support-6.2.16.jar",
          "size": 175412,
          "sha512": "bbf213bcfd41f92e5d0e2ee16f762dd4609584252c63e0e0139674359846ed42b5484b7cf5ed8259532c9988b08560ff91044c1d0e4fb0b035d824b9c06eace1",
          "sha256": "d292ddb7eb99eda8adddd9c818a69bb06d39b50405473e9fded7dd268183175c",
          "sha1": "5894b963f121c50c606cb34c4fc876bb4394772c",
          "md5": "eae900ff12246dde95c07857050715a6"
        }
      ]
    }
  ]
}
