{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-actuator",
    "version": "3.5.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.11"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator-autoconfigure",
          "version": {
            "requires": "3.5.11"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-jakarta9",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.5.11.jar",
          "url": "spring-boot-starter-actuator-3.5.11.jar",
          "size": 4807,
          "sha512": "b38ffbef739ada22093a431ee3b9fae86b2e944a8e505857c8fe6e0f85d6968430ffb4fcdc1fa682b3a9840d8ad509a230a62dd027af9d304245976864cb327d",
          "sha256": "16d0ccff9381ff0a7dc100da05e4b346e944edfa218fd13e4e85b61df5acbfdc",
          "sha1": "ed482b3fdb6ddb2e94b6139387506d4338bea1f2",
          "md5": "54c0662515353da19c65880050d45121"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.11"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator-autoconfigure",
          "version": {
            "requires": "3.5.11"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-jakarta9",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.5.11.jar",
          "url": "spring-boot-starter-actuator-3.5.11.jar",
          "size": 4807,
          "sha512": "b38ffbef739ada22093a431ee3b9fae86b2e944a8e505857c8fe6e0f85d6968430ffb4fcdc1fa682b3a9840d8ad509a230a62dd027af9d304245976864cb327d",
          "sha256": "16d0ccff9381ff0a7dc100da05e4b346e944edfa218fd13e4e85b61df5acbfdc",
          "sha1": "ed482b3fdb6ddb2e94b6139387506d4338bea1f2",
          "md5": "54c0662515353da19c65880050d45121"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.5.11-javadoc.jar",
          "url": "spring-boot-starter-actuator-3.5.11-javadoc.jar",
          "size": 4807,
          "sha512": "734df112908aaf11f466285fa6cb4ce147d7e6bcaf87a215a9508252193a9b5988eeff0a6440057569d43ae6bb16aef310f0a342f7524992a34f273e380f2e3a",
          "sha256": "8386e62acf4e09e0001b42f5d6d465e64be6293bf7ae593c6a676ec76b010561",
          "sha1": "b1ca4cf9be5f7f15cbad8f98088a0dcc95ac7776",
          "md5": "74e93db198e3f5294cd70ad38b125546"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.5.11-sources.jar",
          "url": "spring-boot-starter-actuator-3.5.11-sources.jar",
          "size": 4807,
          "sha512": "734df112908aaf11f466285fa6cb4ce147d7e6bcaf87a215a9508252193a9b5988eeff0a6440057569d43ae6bb16aef310f0a342f7524992a34f273e380f2e3a",
          "sha256": "8386e62acf4e09e0001b42f5d6d465e64be6293bf7ae593c6a676ec76b010561",
          "sha1": "b1ca4cf9be5f7f15cbad8f98088a0dcc95ac7776",
          "md5": "74e93db198e3f5294cd70ad38b125546"
        }
      ]
    }
  ]
}
